# Exercícios Pandas

## Exercício 1

Leia o arquivo actors.csv e faça os seguintes cálculos sobre o conjunto de dados utilizando Pandas

• O ator/atriz com maior número de filmes e o respectivo número de filmes.

• A média do número de filmes.

• O ator/atriz com a maior média por filme.

• O nome do(s) filme(s) mais frequente(s) e sua respectiva frequência.

## Exercício 2

Leia o arquivo csv googleplaystore.csv e realize as seguintes atividades sobre o dataset utilizando Pandas:

• Faça um gráfico de barras contendo os top 5 apps por número de instalação.

• Faça um gráfico de pizza (pie chart) mostrando as categorias de apps existentes no dataset de acordo com a frequência em que elas aparecem.

• Mostre qual o app mais caro existente no dataset.

• Mostre quantos apps são classificados como “Mature 17+”.

• Mostre o top 10 apps por número de reviews bem como o respectivo número de reviews. Ordene a lista de forma decrescente por número de reviews.

## Exercício 3

Leia o arquivo csv wines_SPA.csv e realize as seguintes atividades sobre o dataset utilizando Pandas:

• Mostre qual a vinícola (winery) que possui o maior número de reviews (num_reviews) nos últimos 20 anos.

• Mostre quais são as 5 regiões com a média de preço mais alta e mais baixa.

• A acidez (acidity) varia entre valores até 5, mostre a média de acidez por ano em todo o intervalo existente na coluna ano (year).

• Mostre qual vinho (wine) possui o maior número de safras em todo o intervalo existente na coluna ano (year).

# Exercícios NumPy

## Exercício 1

Crie um array 5x5 com a sequência 1...25 (incluso) e faça a soma dos elementos da diagonal.

In [9]:
import numpy as np
array = np.array(range(1,26))
print('Array: \n', array, '\n Forma do array:', array.shape, '\n')
new_array= array.reshape((5, 5))
print('Array 5 x 5: \n', new_array, '\n Forma do array: ', new_array.shape, '\n')
diagonal = np.diagonal(new_array)
print('Diagonal do Array: \n', diagonal, '\n')
print('Soma dos elementos da diagonal: ', np.sum(diagonal))

Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25] 
 Forma do array: (25,) 

Array 5 x 5: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 
 Forma do array:  (5, 5) 

Diagonal do Array: 
 [ 1  7 13 19 25] 

Soma dos elementos da diagonal:  65


## Exercício 2

Crie um array 5x5 com a sequência de números pares entre 0...50 (incluso) e faça as seguintes operações:

• Soma das linhas

• Soma das Colunas

• Média dos elementos da última linha

• Média dos elementos da última coluna

In [13]:
import numpy as np
array = np.array(range(0, 51, 2))
print('Array: \n', array, '\n')
new_array = array.reshape((5, 5))


Array: 
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50] 



ValueError: cannot reshape array of size 26 into shape (5,5)

## Exercício 3

Dado o array 2D abaixo, substitua o seu maior valor por 0.

• np.random.normal(0, 3, size=(5, 5))

In [17]:
import numpy as np
array = np.random.normal(0, 3, size=(5, 5))
print('Array Numpy: \n', array, '\n')
bigger_el = np.max(array)
print('Maior elemento do array: \n', bigger_el, '\n')
array[array == bigger_el] = 0
print('Substituindo valores: \n', array )

Array Numpy: 
 [[ 4.54144158  0.34972828  0.35023585 -2.06185305 -0.11831187]
 [-1.15066199  2.7973944   0.55537875  5.02401118 -1.91742797]
 [-0.98385368  0.79381043  1.07788091 11.16074087  1.23287476]
 [-3.35035426 -0.89072546 -0.2758325  -0.7046704  -0.62417932]
 [ 5.53266499 -3.89325404 -2.55086806  4.17592872  4.21652661]] 

Maior elemento do array: 
 11.160740873061314 

Substituindo valores: 
 [[ 4.54144158  0.34972828  0.35023585 -2.06185305 -0.11831187]
 [-1.15066199  2.7973944   0.55537875  5.02401118 -1.91742797]
 [-0.98385368  0.79381043  1.07788091  0.          1.23287476]
 [-3.35035426 -0.89072546 -0.2758325  -0.7046704  -0.62417932]
 [ 5.53266499 -3.89325404 -2.55086806  4.17592872  4.21652661]]


## Exercício 4

A partir das arrays abaixo, caso seja possível, realize o produto das mesmas:

• np.random.uniform(size=(5, 3))

• np.random.uniform(size=(3, 4))

In [35]:
import numpy as np

array_1 = np.random.uniform(size=(5, 3))
array_2 = np.random.uniform(size=(3, 4))
print('Array Numpy 01: \n', array_1, '\n')
print('Array Numpy 02: \n', array_2, '\n')

array_3 = np.dot(array_1, array_2)
print('Produto dos Arrays Numpy: \n', array_3, '\n')

Array Numpy 01: 
 [[0.96283344 0.79132353 0.58504042]
 [0.88927244 0.81847994 0.30253998]
 [0.01783104 0.2001454  0.14262327]
 [0.84263986 0.32918936 0.63578945]
 [0.90463708 0.27955251 0.80117518]] 

Array Numpy 02: 
 [[0.4519881  0.1802943  0.74802938 0.69263676]
 [0.50030996 0.00770025 0.66099316 0.16339944]
 [0.32076746 0.98188971 0.2271187  0.87805776]] 

Produto dos Arrays Numpy: 
 [[1.01875823 0.75413194 1.37616076 1.30989494]
 [0.9084792  0.46369415 1.27492404 1.01532953]
 [0.15394306 0.14479632 0.17802529 0.17028555]
 [0.74950047 0.77873312 0.99231096 1.19569256]
 [0.80573903 0.9519192  1.04343928 1.37574171]] 



## Exercício 5

Dado o array abaixo, converta-o para um array do tipo int32.

• np.arange(9, dtype=np.float32).reshape(3, 3)

In [27]:
import numpy as np

array = np.arange(9, dtype=np.float32).reshape(3, 3)
print('Array Numpy: \n', array, '\n')
print('List: \n', array.tolist(), '\n')
list_to_array = np.array(array.tolist(), dtype=np.int32)
print('Array Numpy convertido: \n', list_to_array, '\n')

Array Numpy: 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] 

List: 
 [[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]] 

Array Numpy convertido: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 



## Exercício 6

Dado o array abaixo, some 10 em todos os elementos da última coluna.

• np.random.uniform(size=(8, 8))

In [28]:
import pandas as pd

array = np.random.uniform(size=(8, 8))
print('Array Numpy: \n', array, '\n')
new_array = 10 + array
print('New Array Numpy: \n', new_array, '\n')

Array Numpy: 
 [[0.28718189 0.67286187 0.30741605 0.38794014 0.5625901  0.98710653
  0.13749034 0.7416226 ]
 [0.20922001 0.39215922 0.45377661 0.88534094 0.0586739  0.45884635
  0.75104703 0.25911796]
 [0.63454374 0.79158911 0.92265604 0.39600299 0.0575524  0.20280185
  0.79518536 0.55324356]
 [0.57350758 0.87475948 0.45008437 0.03238764 0.23560215 0.4508947
  0.61821757 0.59828692]
 [0.47251415 0.24389477 0.52279359 0.43510507 0.64978028 0.17838131
  0.05558135 0.31886208]
 [0.04813614 0.1835944  0.73209101 0.6109577  0.77197981 0.72749363
  0.60578479 0.82590751]
 [0.64186037 0.29571695 0.25132711 0.3974988  0.8911412  0.59838545
  0.50682692 0.84724064]
 [0.98974625 0.07316472 0.03311386 0.12662416 0.43603435 0.31773999
  0.34661913 0.91565578]] 

New Array Numpy: 
 [[10.28718189 10.67286187 10.30741605 10.38794014 10.5625901  10.98710653
  10.13749034 10.7416226 ]
 [10.20922001 10.39215922 10.45377661 10.88534094 10.0586739  10.45884635
  10.75104703 10.25911796]
 [10.63454374 10.7

## Exercício 7

Dados os dois arrays 2x4 abaixo, empilhe ambos formando um novo array 4x4.

• np.array([[0,3,4,5], [7, 10, 9, 2]])

• np.array([[1,4,9,12], [15, 22, 19, 17]])


In [30]:
import numpy as np

array_01 = np.array([[0,3,4,5], [7, 10, 9, 2]])
array_02 = np.array([[1,4,9,12], [15, 22, 19, 17]])
print('Array Numpy 01: \n', array_01, '\n', 'Forma do array numpy: \n', array_01.shape, '\n')
print('Array Numpy 02: \n', array_02, '\n', 'Forma do array numpy: \n', array_02.shape, '\n')
array_03 = np.concatenate((array_01, array_02))
print('New Array Numpy: \n', array_03, '\n', 'Forma do array numpy: \n', array_03.shape)


Array Numpy 01: 
 [[ 0  3  4  5]
 [ 7 10  9  2]] 
 Forma do array numpy: 
 (2, 4) 

Array Numpy 02: 
 [[ 1  4  9 12]
 [15 22 19 17]] 
 Forma do array numpy: 
 (2, 4) 

New Array Numpy: 
 [[ 0  3  4  5]
 [ 7 10  9  2]
 [ 1  4  9 12]
 [15 22 19 17]] 
 Forma do array numpy: 
 (4, 4)


## Exercício 8

Dado o array definido por np.arange(25).reshape(5, 5), realize as seguintes operações sem utilizar nenhum tipo de loop (for / while):

• A média das linhas 0, 2 e 3.

• A média das colunas 0, 1 e 4.

• A soma dos elementos das duas diagonais.

In [67]:
import numpy as np

array = np.arange(25).reshape(5, 5)
print('Array Numpy: \n', array, '\n \n ')
print('Linha 0: ', array[0])
print('Linha 2: ', array[2])
print('Linha 3: ', array[3], '\n')
print('Coluna 0: ', array[:, 0] )
print('Coluna 1: ', array[:, 1])
print('Coluna 4: ', array[:, 4],'\n' )

media_linhas = np.mean(array, axis = 1)

print('Média das linhas: ', np.mean(array))
print('Média de cada linha: ', array.mean(axis=1) )
print('Média da linha 0: ',  np.mean(array[0]))
print('Média da linha 2: ',  np.mean(array[2]))
print('Média da linha 3: ',  np.mean(array[3]), '\n')

print('Média das colunas: ')
print('Média de cada coluna: ', array.mean(axis=0) )
print('Média da coluna 0: ', np.mean(array[:,0]))
print('Média da coluna 1: ', np.mean(array[:,1]))
print('Média da coluna 4: ', np.mean(array[:,4]), '\n')

diagonal_01 = np.diagonal(array)
diagonal_02 = np.diagonal(array[-1])
print('Diagonal 01: ', diagonal_01)
print('Diagonal 02: ', diagonal_02)
print('Soma da diagonal 01: ')
print('Soma da diagonal 02: ')
print('Soma das duas diagonais: ', '\n')


Array Numpy: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 
 
 
Linha 0:  [0 1 2 3 4]
Linha 2:  [10 11 12 13 14]
Linha 3:  [15 16 17 18 19] 

Coluna 0:  [ 0  5 10 15 20]
Coluna 1:  [ 1  6 11 16 21]
Coluna 4:  [ 4  9 14 19 24] 

Média das linhas:  12.0
Média de cada linha:  [ 2.  7. 12. 17. 22.]
Média da linha 0:  2.0
Média da linha 2:  12.0
Média da linha 3:  17.0 

Média das colunas:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Média de cada coluna:  [10. 11. 12. 13. 14.]
Média da coluna 0:  10.0
Média da coluna 1:  11.0
Média da coluna 4:  14.0 



ValueError: diag requires an array of at least two dimensions

## Exercício 9

Dado o array abaixo, selecione os valores Pares e todos os valores maiores que 8, seu código não deve conter nenhum tipo de loop (for / while):

• np.arange(25).reshape(5, 5)

In [40]:
import numpy as np

array = np.arange(25).reshape(5, 5)
print('Array Numpy: \n', array, '\n')
print('Pares do Array Numpy: \n', array[array%2==0], '\n')
print('Valores > 8 do Array Numpy: \n', array[array>8], '\n')
new_array = array[(array%2==0)&(array>8)]
print('Seleção de valores pares e valores > 8 do Array Numpy: \n', new_array, '\n')

Array Numpy: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

Pares do Array Numpy: 
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24] 

Valores > 8 do Array Numpy: 
 [ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 

Seleção de valores pares e valores > 8 do Array Numpy: 
 [10 12 14 16 18 20 22 24] 



## Exercício 10

Dado o array 2D abaixo, substitua os 5 menores valores por -1, seu código não deve conter nenhum tipo de loop (for / while):

• a = np.random.randint(0, 50, (5, 5))

In [52]:
import numpy as np 

array = np.random.randint(0, 50, (5, 5))
print('Array Numpy: \n', array, '\n')



print('Array Numpy ordenado: \n', '' , '\n')

print('New Array Numpy: \n', 'futuro resultado', '\n')


Array Numpy: 
 [[12 26 42 46 46]
 [11 10 49 17 11]
 [10 40 49 16 47]
 [16 22 39 45 15]
 [13 15  0 14 27]] 

[[12, 26, 42, 46, 46], [11, 10, 49, 17, 11], [10, 40, 49, 16, 47], [16, 22, 39, 45, 15], [13, 15, 0, 14, 27]]
Array Numpy ordenado: 
  

New Array Numpy: 
 futuro resultado 

